version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/fruitables
      JWT_SECRET: your_jwt_secret_key
    ports:
      - '3000:3000'
    depends_on:
      - database

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      API_URL: http://api:3000
    ports:
      - '4200:4200'
    depends_on:
      - api

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fruitables
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
